# Generated by Django 5.1.1 on 2024-10-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridapp', '0002_alter_student_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
